dataset:
  name: mnist6_seed1
  num_classes: 6
  pre_size: 28
  image_size: 28

  interpolation: bilinear
  normalization_type: mnist

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  split_names: [train, val, test, out]

  train:
    dataset_class: ImglistDataset
    data_dir: /mnt/data-hdd/wgk/OpenOOD/data/Knot_Tying/fold1/train
    imglist_pth: /mnt/data-hdd/wgk/OpenOOD/data/Knot_Tying/fold1/train.txt
    batch_size: 256
    shuffle: True
  val:
    dataset_class: ImglistDataset
    data_dir: /mnt/data-hdd/wgk/OpenOOD/data/Knot_Tying/fold1/test
    imglist_pth: /mnt/data-hdd/wgk/OpenOOD/data/Knot_Tying/fold1/test.txt
    batch_size: 256
    shuffle: False
  test:
    dataset_class: ImglistDataset
    data_dir: /mnt/data-hdd/wgk/OpenOOD/data/Knot_Tying/fold1/test
    imglist_pth: /mnt/data-hdd/wgk/OpenOOD/data/Knot_Tying/fold1/test.txt
    batch_size: 256
    shuffle: False
  out:
    dataset_class: ImglistDataset
    data_dir: /mnt/data-hdd/wgk/OpenOOD/data/Knot_Tying/fold1/test
    imglist_pth: /mnt/data-hdd/wgk/OpenOOD/data/Knot_Tying/fold1/out.txt
    batch_size: 256
    shuffle: False
