ood_dataset:
  name: mnist6_seed1_osr
  num_classes: 6
  pre_size: 28
  image_size: 28

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  dataset_class: ImglistDataset
  batch_size: 128
  shuffle: False

  split_names: [val, osr]
  val:
    data_dir: /mnt/data-hdd/wgk/OpenOOD/data/Knot_Tying/fold1/test
    imglist_pth: /mnt/data-hdd/wgk/OpenOOD/data/Knot_Tying/fold1/test.txt
  osr:
    datasets: [mnist4]
    mnist4:
      data_dir: /mnt/data-hdd/wgk/OpenOOD/data/Knot_Tying/fold1/test
      imglist_pth: /mnt/data-hdd/wgk/OpenOOD/data/Knot_Tying/fold1/out.txt
